### ISSUE TITLE
vim/shared.lua:63: s: expected string, got table

### ISSUE THREAD

**Issue by BlackLight** [aloussase/telescope-gradle.nvim#1]
Steps to replicate:

- Initialize an empty project via `gradle init` (in my case, I have initialized an empty Kotlin application)

- Open any file in the project

- Run `:Telescope gradle` and select a task (I have tried with `run`)

The execution fails and the following stack trace is reported on the logs:

```text
vim/shared.lua:63: s: expected string, got table
stack traceback:
^I[C]: in function 'error'
^Ivim/shared.lua:608: in function 'validate'
^Ivim/shared.lua:63: in function 'gsplit'
^Ivim/shared.lua:128: in function 'split'
^I...le.nvim/lua/telescope/_extensions/gradle/task_runner.lua:7: in function 'handle_error'
^I...le.nvim/lua/telescope/_extensions/gradle/task_runner.lua:37: in function <...le.nvim/lua/telescope/_extensions/gradle/task_runner.lua:36>
```

**Comment by aloussase** [comment]
Hi! Thanks for reporting the error. I think it should be fixed now. Tell me after you check!

**Comment by BlackLight** [comment]
Thanks! I can confirm that it works after pulling https://github.com/aloussase/telescope-gradle.nvim/commit/e20d5fec180bedcd884ed5769feb546d415f06e3
